### ISSUE TITLE
Triger AttributeError "X not found" when use  layer parameter in mu.tl.embedding

### ISSUE THREAD

**Issue by liuzj039** [PMBio/muon#29]
**Describe the bug**
Triger AttributeError "X not found" when use  layer parameter in mu.tl.embedding.

**To Reproduce**
`mu.pl.embedding(
    md,
    "X_umap",
    color=[*some gene*],
    cmap="Reds",
    layer="sct_corrected",
)`

then a attribute error was triggered

> ---------------------------------------------------------------------------
>AttributeError                            Traceback (most recent call last)
>
>~/softwares/anaconda3/lib/python3.8/site-packages/muon/_core/plot.py in embedding(data, basis, color, use_raw, layer, >**kwargs)
 >   120                 if layer is not None:
  >  121                     if layer in data.mod[m].layers:
>--> 122                         fmod_adata.X = data.mod[m][:, mod_keys].layers[layer].X
 >   123                         if use_raw:
  >  124                             warnings.warn(f"Layer='{layer}' superseded use_raw={use_raw}")
>
>~/softwares/anaconda3/lib/python3.8/site-packages/scipy/sparse/base.py in __getattr__(self, attr)
 >   685             return self.getnnz()
  >  686         else:
>--> 687             raise AttributeError(attr + " not found")
 >   688 
  >  689     def transpose(self, axes=None, copy=False):
>
>AttributeError: X not found

**Additional context**
This error appears to be caused by a typo. In fact a simple deletion of the `.X` will fix this bug.https://github.com/PMBio/muon/blob/e77bbf3a2acb1c92dae4c13419cd7335602c2735/muon/_core/plot.py#L122

Thanks developers for providing such a great tool.

**Comment by liuzj039** [comment]
It is also a typo in mudata.py https://github.com/PMBio/muon/blob/e77bbf3a2acb1c92dae4c13419cd7335602c2735/muon/_core/mudata.py#L786

**Comment by ilia-kats** [comment]
This should be fixed in master, could you test it and report back?

**Comment by liuzj039** [comment]
Muon is also working well in my environment now.
Thank you for your quick reply！
