### ISSUE TITLE
Simplify sparsity check

### ISSUE THREAD

**Issue by WeilerP** [PMBio/muon#34]
## Description

I may be missing something: Is there a reason why `scipy`'s `issparse` function is not used e.g. here:

https://github.com/PMBio/muon/blob/912b52ae874b7ddc028b3ea0fc166871fd9e41b1/muon/_atac/preproc.py#L96

**Comment by gtca** [comment]
Thank you! 
I don't think there's any particular reason.
Just to ask for another pair of eyes, @ilia-kats?

**Comment by ilia-kats** [comment]
`issparse` should work, as far as I can tell.
