### ISSUE TITLE
ATAC QC error

### ISSUE THREAD

**Issue by taopeng1100** [PMBio/muon#37]
I got this error from running ac.pl.fragment_histogram(atac, region='chr1:1-2000000')
KeyError                                  Traceback (most recent call last)
<ipython-input-37-89aa4ae76e04> in <module>
----> 1 ac.pl.fragment_histogram(atac, region='chr1:1-2000000')

~\Anaconda3\lib\site-packages\muon\_atac\plot.py in fragment_histogram(data, region, groupby)
    330         raise TypeError("Expected AnnData or MuData object with 'atac' modality")
    331 
--> 332     fragment_path = adata.uns["files"]["fragments"]
    333     fragments = tools.fetch_regions_to_df(fragment_path=fragment_path, features=region)
    334 

~\Anaconda3\lib\site-packages\anndata\compat\_overloaded_dict.py in __getitem__(self, key)
     98             return self.overloaded[key].get()
     99         else:
--> 100             return self.data[key]
    101 
    102     def __setitem__(self, key, value):

KeyError: 'files'

I got another error by running ac.tl.nucleosome_signal(atac, n=1e6)

KeyError                                  Traceback (most recent call last)
<ipython-input-38-4b9a55fd5249> in <module>
----> 1 ac.tl.nucleosome_signal(atac, n=1e6)

~\Anaconda3\lib\site-packages\muon\_atac\tools.py in nucleosome_signal(data, n, nucleosome_free_upper_bound, mononuleosomal_upper_bound)
   1031 
   1032     if "files" not in adata.uns or "fragments" not in adata.uns["files"]:
-> 1033         raise KeyError(
   1034             "There is no fragments file located yet. Run muon.atac.tl.locate_fragments first."
   1035         )

KeyError: 'There is no fragments file located yet. Run muon.atac.tl.locate_fragments first.'

Not sure what to do?

**Comment by gtca** [comment]
Hey, in order to work with fragments, a fragments file (with a tabix index) is required. It's a BED-like file, and you can find more information about it [for instance here](https://support.10xgenomics.com/single-cell-atac/software/pipelines/latest/output/fragments).

This is a large file that is not loaded into the AnnData object but rather a path to the file is recorded.
For 10X Genomics CellRanger ATAC output, the reader in `muon.atac` will pick the file automatically.

It seems like there has been no fragments file located and, as indicated by the error message, it has to be located with `ac.tl.locate_fragments()`.

**Comment by maxim-h** [comment]
I've had this issue while going through the tutorial. 

The `ac.tl.locate_fragments()` solution as suggested by @gtca works, but it's not clear why it is required from the tutorial. 

The reason, I believe, is that tutorial assumes the presence of `pysam` in which case `mu.read_10x_h5` will automatically add the fragment file. But `pysam` not in the `pyproject.toml`. If `pysam` is not present it will show a little warning that is very easy to miss (at least for me). 

So the solution would probably be to just explicitly add `pysam` as a dependency even though it may not be necessary for all use cases.

**Comment by gtca** [comment]
Thanks, @maxim-h, this is a fair point. I believe we can improve error & warning messages.

The one that this thread has started with seems to be good enough already though? It does provide an action point:

```
KeyError: 'There is no fragments file located yet. Run muon.atac.tl.locate_fragments first.'
```

Currently, I would argue for continuing not having `pysam` as a hard dependency for `muon` — even when working with ATAC-seq data it might not be required, depending on the task, not speaking of other omics.
Maybe we can take advantage of features like [`extras` in poetry](https://python-poetry.org/docs/pyproject/) — or [`requires-extra` in flit](https://flit.readthedocs.io/en/latest/pyproject_toml.html), which we're currently using.

**Comment by gtca** [comment]
As this has been recently addressed e.g. in 60c979b6442903228dbaa5f4d9807fc4f66a8967 and 17eb76c183e0739b96d634963c6e82a02c71c4b8, I'll close it for now. Feel free to re-open or to open a new one if there are other suggestions how to improve user experience with ATAC while it's a part of muon with optional dependencies.
